authorName: littlepure
experimentName: FC_size_experiment
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 12
#choice: local, remote, pai, kubeflow
trainingServicePlatform: local
searchSpacePath: /home/tensor/jupyter/wsz/pytorch-vgg/NNI/search_space_3.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
#assessor:
#  #choice: Medianstop
#  builtinAssessorName: Medianstop
#  classArgs:
#    #choice: maximize, minimize
#    optimize_mode: maximize
trial:
  command: python3 train_nni.py
  codeDir: /home/tensor/jupyter/wsz/pytorch-vgg
  gpuNum: 1
localConfig:
  useActiveGpu: true